# Use Node.js LTS
FROM node:18

# Set working dir
WORKDIR /app

# Copy package.json and install deps
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose port
EXPOSE 5000

# Run the app
CMD ["node", "dist/server.js"]
